### ISSUE TITLE
Doesn't build under Fedora 27 4.14.16-300

### ISSUE THREAD

**Issue by charlesUnixPro** [lemonsqueeze/uncached_ram_lkm#1]
/home/cac/Projects/LocalBuilds/uncached-ram-lkm/uncached_ram.c:73:4: error: implicit declaration of function ‘set_memory_wb’; did you mean ‘add_memory’? [-Werror=implicit-function-declaration]
    set_memory_wb((unsigned long)addr, 1);
    ^~~~~~~~~~~~~

/home/cac/Projects/LocalBuilds/uncached-ram-lkm/uncached_ram.c:101:7: error: implicit declaration of function ‘set_memory_uc’; did you mean ‘add_memory’? [-Werror=implicit-function-declaration]
   if (set_memory_uc((unsigned long)addr, 1))
       ^~~~~~~~~~~~~

diff --git a/uncached_ram.c b/uncached_ram.c
index c3dd618..24b0580 100644
--- a/uncached_ram.c
+++ b/uncached_ram.c
@@ -13,7 +13,7 @@
 
 #include <linux/page-flags.h>
 #include <asm/cacheflush.h>
-
+#include <linux/set_memory.h>
 #include <linux/device.h>
 #include <linux/fs.h>
 #include <linux/mm.h>

**Comment by avose** [comment]
This was fixed for me in Ubuntu (`Linux myboxname 5.3.0-46-generic #38~18.04.1-Ubuntu SMP Tue Mar 31 04:17:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux` by adding `#include <asm/set_memory.h>`) after the existing `#include <asm/cacheflush.h>`.

to the file `uncached_ram.c`.

**Comment by lemonsqueeze** [comment]
Issue should be fixed by this [pull request](https://github.com/lemonsqueeze/uncached-ram-lkm/pull/2).
